# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3559c573ebea1158af9a2318e6d30afbb4be4efd303b5beb1a241c856c379359fc15e030beaa293e2538377ac8811c5c8011a868bae54688dcc9489afbf37860
  facebook_app_id: 884014881694834
  facebook_app_secret: 96dfdd730567546e9a4af683e2a31ad2
  vk_app_id: 5084096
  vk_app_secret: D7COd3rBcrxN2v7xqWCq
  twitter_app_id: EocawsZGpMOIGPfoPTw8aLRbr
  twitter_app_secret: 5HnjQ55X4bOfLqbISFRknBU9SQRIex5zQXa0tY7lFg9lwXEi7n
  instagram_app_id:	f153728ab33e4a1dbc4eedeafd5a88c1
  instagram_app_secret: 3e8b35aca7164085a7663951073ddacb
  jwt_secret: mspXgekK9E4nFFFmGV-PUg
  client_url: http://localhost:9000

test:
  secret_key_base: 11341f98859aafe7084acd5e9212cfe1d45ba64d178ef8b6b07a8f809af4c425925b89b6fc6a6e36138da66737d87122b86a36a4b98fd10385a3c72ea6643787
  jwt_secret: TUxuxjakQvcKCMYc9mH0ug

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  vk_app_id: <%= ENV["VK_APP_ID"] %>
  vk_app_secret: <%= ENV["VK_APP_SECRET"] %>
  jwt_secret: <%= ENV["JWT_SECRET"] %>
  client_url: <%= ENV["CLIENT_URL"] %>
