#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rbenv', '~> 1.7.1'
cookbook 'runit'
cookbook 'ruby_rbenv', git: 'git://github.com/fnichol/chef-rbenv'
cookbook 'nginx', '~> 2.7.6'
cookbook 'postgresql', '~> 4.0.6'
# cookbook 'rbenv', git: 'git://github.com/fnichol/chef-rbenv'
# cookbook 'yum-nginx', '~> 0.1.0'
# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'
# cookbook 'runit'
#   cookbook 'nginx', :git => 'git://github.com/opscode-cookbooks/nginx.git'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
